/**
 * Next.js Custom Document Component
 * 
 * This file customizes the HTML document structure that wraps every page.
 * It handles:
 * - Server-side rendering of Emotion (CSS-in-JS) styles
 * - Loading external fonts (Roboto for Material-UI)
 * - Setting theme color for mobile browsers
 * - HTML language and meta tags
 * 
 * This component only runs on the server during initial page load.
 * It's used to augment the <html> and <body> tags.
 */

import Document, { Html, Head, Main, NextScript } from 'next/document';
import createEmotionServer from '@emotion/server/create-instance';
import theme from '../src/theme';
import createEmotionCache from '../src/createEmotionCache';

/**
 * Custom Document Component
 * 
 * Extends Next.js Document to add custom HTML structure and
 * server-side style injection for Emotion/Material-UI.
 */
export default class MyDocument extends Document {
  render() {
    return (
      // Set document language (currently set to Japanese, can be changed to 'en' for English)
      <Html lang="ja">
        <Head>
          {/* Theme color for mobile browser UI (affects address bar color on mobile) */}
          <meta name="theme-color" content={theme.palette.primary.main} />
          
          {/* Load Roboto font from Google Fonts - Material-UI's default font */}
          <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" />
          
          {/* Load Material Icons font for icon components */}
          <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
          
          {/* Inject critical CSS for Emotion styled components (server-side rendered) */}
          {this.props.emotionStyleTags}
          
        </Head>
        <body>
          {/* Main application content */}
          <Main />
          
          {/* Next.js scripts for hydration and client-side navigation */}
          <NextScript />
        </body>
      </Html>
    );
  }
}

/**
 * getInitialProps for Server-Side Style Injection
 * 
 * This special Next.js method runs on the server before rendering.
 * It extracts critical CSS from Emotion styled components and injects it
 * into the HTML to prevent flash of unstyled content (FOUC).
 * 
 * This ensures styles are rendered on the initial server-side render,
 * improving perceived performance and SEO.
 * 
 * @param {Object} ctx - Next.js document context
 * @returns {Object} Props with emotion style tags
 */
MyDocument.getInitialProps = async (ctx) => {
  // Store the original renderPage function
  const originalRenderPage = ctx.renderPage;
  
  // Create an Emotion cache for this render
  const cache = createEmotionCache();
  
  // Create Emotion server instance for extracting styles
  const { extractCriticalToChunks } = createEmotionServer(cache);

  // Override renderPage to inject Emotion cache into the app
  ctx.renderPage = () => {
    return originalRenderPage({
      enhanceApp: (App) =>
        // Wrap the App component to provide Emotion cache
        function EnhanceApp(props) {
            return <App emotionCache={cache} {...props} />;
        },
    });
  }

  // Get initial props from the base Document class
  const initialProps = await Document.getInitialProps(ctx);
  
  // Extract all CSS generated by Emotion during rendering
  const emotionStyles = extractCriticalToChunks(initialProps.html);
  
  // Convert extracted styles into <style> tags
  const emotionStyleTags = emotionStyles.styles.map((style) => (
    <style
      data-emotion={`${style.key} ${style.ids.join(' ')}`}
      key={style.key}
      // Inject the raw CSS directly into the style tag
      // eslint-disable-next-line react/no-danger
      dangerouslySetInnerHTML={{ __html: style.css }}
    />
  ));

  // Return props with the style tags to be injected in <Head>
  return {
    ...initialProps,
    emotionStyleTags,
  };
};
